name: Run Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.6

    
        - name: Install dependencies
        run: |
          pip install requests pytz python-telegram-bot pymongo python-dotenv apscheduler firebase-admin


    - name: Load .env Variables
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Test MongoDB Connection
  run: mongo --eval "db.stats()"


    - name: Run Telegram Bot
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        while true; do
          python simplrefq.py
        done
