name: Run Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install requests pytz python-telegram-bot pymongo python-dotenv apscheduler firebase-admin

      - name: Run Telegram bot
        run: |
          while true; do
            python simplrefq.py
          done
